#!/usr/bin/env php

<?php

require_once __DIR__.'/vendor/autoload.php';

if (PHP_SAPI !== "cli") {
    exit;
}

$cli = new App\Core\CLI\CLI();

/**
 * Register CORE Commands
 */
$commands = \App\Core\Helpers\FileHelper::getFiles('./App/Core/CLI/Commands');

foreach ($commands as $command) {
    $className = \App\Core\Helpers\StringHelper::removeExtension($command);
    $classPath = 'App\Core\CLI\Commands\\' . $className;
    $commandClassObject = new $classPath($cli);

    $commandName = $commandClassObject->name ?? $className;

    $cli->registerController($commandName, $commandClassObject);
}

foreach ($commands as $command) {
    $className = \App\Core\Helpers\StringHelper::removeExtension($command);
    $classPath = 'App\Core\CLI\Commands\\' . $className;
    $commandClassObject = new $classPath($cli);

    $commandName = $commandClassObject->name ?? $className;

    $cli->registerController($commandName, $commandClassObject);
}

/**
 * Register custom commands
 */
$commands = \App\Core\Helpers\FileHelper::getFiles('./App/Commands');

foreach ($commands as $command) {
    $className = \App\Core\Helpers\StringHelper::removeExtension($command);
    $classPath = 'App\Commands\\' . $className;
    $commandClassObject = new $classPath($cli);

    $commandName = $commandClassObject->name ?? $className;

    $cli->registerController($commandName, $commandClassObject);
}


$cli->runCommand($argv);
